// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUXiEVLTvgX1egfM6gsANIuFRmFq_Vqt4',
    appId: '1:639345974694:web:b64a32c60796a7b29b8367',
    messagingSenderId: '639345974694',
    projectId: 'mytaag-1',
    authDomain: 'mytaag-1.firebaseapp.com',
    storageBucket: 'mytaag-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKW7NY0NI4qqrhrh48CpCTIFapNObxzE',
    appId: '1:639345974694:android:72c445e4d1b018b29b8367',
    messagingSenderId: '639345974694',
    projectId: 'mytaag-1',
    storageBucket: 'mytaag-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY1b-f5yYOwrYgS6kfdJFSDxCgsiPT0sw',
    appId: '1:639345974694:ios:e687c5447d6b55fe9b8367',
    messagingSenderId: '639345974694',
    projectId: 'mytaag-1',
    storageBucket: 'mytaag-1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY1b-f5yYOwrYgS6kfdJFSDxCgsiPT0sw',
    appId: '1:639345974694:ios:fe8b666f20027bb49b8367',
    messagingSenderId: '639345974694',
    projectId: 'mytaag-1',
    storageBucket: 'mytaag-1.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
